version: '3.7'

services:
  spring:
    image: gradle-springboot
    depends_on:
      - yota-mysql
    ports:
      - 8080:8080
    container_name: spring


  yota-mysql:
    container_name: yota-mysql
    image: mysql/mysql-server:8.0
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: yota
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306
    restart: always
